# Generated by Django 2.1.7 on 2019-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='j',
            field=models.CharField(default=23, max_length=2),
            preserve_default=False,
        ),
    ]
