# Generated by Django 2.1.7 on 2019-03-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_url_j'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='j',
        ),
    ]
