# Generated by Django 2.1.7 on 2019-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_url_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='num',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
