# Generated by Django 2.1.7 on 2019-03-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190331_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='unique_id',
        ),
    ]
