# Generated by Django 2.1.7 on 2019-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_url_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='unique_key',
            field=models.CharField(max_length=150),
        ),
    ]
